// Pantone Color of the Year themes (2015-2024)

export interface Theme {
  id: string;
  name: string;
  year: number;
  pantone: string;
  colors: {
    primary: string;
    primaryLight: string;
    primaryDark: string;
    secondary: string;
    secondaryLight: string;
    secondaryDark: string;
    accent: string;
    background: string;
    surface: string;
    text: string;
    textSecondary: string;
    textOnPrimary: string;
    textOnSecondary: string;
    textMuted: string;
    border: string;
    borderLight: string;
    success: string;
    warning: string;
    error: string;
    info: string;
    successBg: string;
    warningBg: string;
    errorBg: string;
    infoBg: string;
    successText: string;
    warningText: string;
    errorText: string;
    infoText: string;
    codeBg: string;
    codeText: string;
    surfaceHover: string;
    surfaceActive: string;
    overlay: string;
  };
}

export const themes: Theme[] = [
  {
    id: 'peach-fuzz',
    name: 'Peach Fuzz',
    year: 2024,
    pantone: 'PANTONE 13-1023',
    colors: {
      primary: '#FFBE98',
      primaryLight: '#FFD4B8',
      primaryDark: '#E89A72',
      secondary: '#F4A582',
      secondaryLight: '#F8C0A2',
      secondaryDark: '#E08A62',
      accent: '#FFE4D6',
      background: '#FFF8F5',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFD4B8',
      borderLight: '#FFE9DD',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF8F5',
      surfaceActive: '#FFE9DD',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'viva-magenta',
    name: 'Viva Magenta',
    year: 2023,
    pantone: 'PANTONE 18-1750',
    colors: {
      primary: '#BE3455',
      primaryLight: '#D65577',
      primaryDark: '#9B2642',
      secondary: '#E84B6E',
      secondaryLight: '#F06F8C',
      secondaryDark: '#D02750',
      accent: '#FFE4E9',
      background: '#FFF5F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#E2B3BF',
      borderLight: '#F0D9DF',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF5F7',
      surfaceActive: '#FFE4E9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'very-peri',
    name: 'Very Peri',
    year: 2022,
    pantone: 'PANTONE 17-3938',
    colors: {
      primary: '#6667AB',
      primaryLight: '#8889C9',
      primaryDark: '#4F508A',
      secondary: '#9394D1',
      secondaryLight: '#AFAFDF',
      secondaryDark: '#7879B3',
      accent: '#E6E6F5',
      background: '#F7F7FC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#C7C7E2',
      borderLight: '#DCDCEE',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7F7FC',
      surfaceActive: '#E6E6F5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'illuminating-gray',
    name: 'Illuminating + Gray',
    year: 2021,
    pantone: 'PANTONE 17-5104 + 13-0647',
    colors: {
      primary: '#939597',
      primaryLight: '#B8BABC',
      primaryDark: '#6E7072',
      secondary: '#F5DF4D',
      secondaryLight: '#F8E77D',
      secondaryDark: '#E5CF3D',
      accent: '#FFF9D9',
      background: '#F7F7F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E2E8F0',
      borderLight: '#EDF2F7',
      success: '#48BB78',
      warning: '#F5DF4D',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFF9D9',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#975A16',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7F7F7',
      surfaceActive: '#EDF2F7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'classic-blue',
    name: 'Classic Blue',
    year: 2020,
    pantone: 'PANTONE 19-4052',
    colors: {
      primary: '#0F4C81',
      primaryLight: '#4A7BA7',
      primaryDark: '#0A3659',
      secondary: '#5B9BD5',
      secondaryLight: '#8BBAE0',
      secondaryDark: '#4886C5',
      accent: '#D6E8F7',
      background: '#F0F7FF',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#B3D4E8',
      borderLight: '#D6E8F7',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#5B9BD5',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#D6E8F7',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#0F4C81',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F0F7FF',
      surfaceActive: '#D6E8F7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'living-coral',
    name: 'Living Coral',
    year: 2019,
    pantone: 'PANTONE 16-1546',
    colors: {
      primary: '#FF6F61',
      primaryLight: '#FF9287',
      primaryDark: '#E65548',
      secondary: '#FFB5AE',
      secondaryLight: '#FFC8C3',
      secondaryDark: '#FF9C95',
      accent: '#FFE9E6',
      background: '#FFF5F4',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFCCC7',
      borderLight: '#FFE0DD',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF5F4',
      surfaceActive: '#FFE9E6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'ultra-violet',
    name: 'Ultra Violet',
    year: 2018,
    pantone: 'PANTONE 18-3838',
    colors: {
      primary: '#5F4B8B',
      primaryLight: '#8477AB',
      primaryDark: '#473766',
      secondary: '#9B89BD',
      secondaryLight: '#B5A4CC',
      secondaryDark: '#8774AA',
      accent: '#E8E3F0',
      background: '#F5F3F9',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#D1C4E3',
      borderLight: '#E8E3F0',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#9B89BD',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#E8E3F0',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#473766',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F5F3F9',
      surfaceActive: '#E8E3F0',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'greenery',
    name: 'Greenery',
    year: 2017,
    pantone: 'PANTONE 15-0343',
    colors: {
      primary: '#88B04B',
      primaryLight: '#A8C97B',
      primaryDark: '#6D8C3C',
      secondary: '#B5D47C',
      secondaryLight: '#C8DF9A',
      secondaryDark: '#A0C060',
      accent: '#E8F3D6',
      background: '#F5FAF0',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#D4E5BC',
      borderLight: '#E8F3D6',
      success: '#88B04B',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#E8F3D6',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#6D8C3C',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F5FAF0',
      surfaceActive: '#E8F3D6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'rose-serenity',
    name: 'Rose Quartz + Serenity',
    year: 2016,
    pantone: 'PANTONE 13-1520 + 15-3919',
    colors: {
      primary: '#F7CAC9',
      primaryLight: '#FADED9',
      primaryDark: '#E5B3B2',
      secondary: '#92A8D1',
      secondaryLight: '#AFC0DC',
      secondaryDark: '#7A92C6',
      accent: '#EDF2F9',
      background: '#FBF7F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E5D4E0',
      borderLight: '#EDF2F9',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#92A8D1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EDF2F9',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FBF7F7',
      surfaceActive: '#EDF2F9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'marsala',
    name: 'Marsala',
    year: 2015,
    pantone: 'PANTONE 18-1438',
    colors: {
      primary: '#955251',
      primaryLight: '#B57876',
      primaryDark: '#764140',
      secondary: '#C9908E',
      secondaryLight: '#D9ADA9',
      secondaryDark: '#B57876',
      accent: '#F0E4E3',
      background: '#FAF5F5',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#DCC9C8',
      borderLight: '#F0E4E3',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FAF5F5',
      surfaceActive: '#F0E4E3',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  // Pastel Themes Collection
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#C7B8EA',
      primaryLight: '#DDD2F4',
      primaryDark: '#B09FDB',
      secondary: '#E0D5F7',
      secondaryLight: '#EDE6FA',
      secondaryDark: '#D3C4F0',
      accent: '#F5F1FF',
      background: '#FDFCFF',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E0D5F7',
      borderLight: '#EDE6FA',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FDFCFF',
      surfaceActive: '#F5F1FF',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#B4E7CE',
      primaryLight: '#CDEFD9',
      primaryDark: '#9BDABF',
      secondary: '#A8E6CF',
      secondaryLight: '#C4F0DD',
      secondaryDark: '#92D9BC',
      accent: '#E8FAF1',
      background: '#F8FFFC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#C4F0DD',
      borderLight: '#E8FAF1',
      success: '#A8E6CF',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8FAF1',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F8555',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F8FFFC',
      surfaceActive: '#E8FAF1',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'powder-blue',
    name: 'Powder Blue',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#B5D8EB',
      primaryLight: '#CEEBF5',
      primaryDark: '#9CC7DD',
      secondary: '#A8D8EA',
      secondaryLight: '#C3E5F0',
      secondaryDark: '#8FC8DC',
      accent: '#E5F4F9',
      background: '#F7FCFE',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#C3E5F0',
      borderLight: '#E5F4F9',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5D8EB',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#E5F4F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7FCFE',
      surfaceActive: '#E5F4F9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'butter-cream',
    name: 'Butter Cream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFF4B8',
      primaryLight: '#FFF9D6',
      primaryDark: '#FFEB9A',
      secondary: '#FFECA8',
      secondaryLight: '#FFF3C8',
      secondaryDark: '#FFE590',
      accent: '#FFFBED',
      background: '#FFFEF8',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFF3C8',
      borderLight: '#FFFBED',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFEF8',
      surfaceActive: '#FFFBED',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFD1DC',
      primaryLight: '#FFE4EC',
      primaryDark: '#FFBDCC',
      secondary: '#FFC9DD',
      secondaryLight: '#FFDEE8',
      secondaryDark: '#FFB4D0',
      accent: '#FFF0F5',
      background: '#FFFAFC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFDEE8',
      borderLight: '#FFF0F5',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFAFC',
      surfaceActive: '#FFF0F5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'peach-cream',
    name: 'Peach Cream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFD7BA',
      primaryLight: '#FFE6D5',
      primaryDark: '#FFC7A0',
      secondary: '#FFDAB9',
      secondaryLight: '#FFE9D6',
      secondaryDark: '#FFC89E',
      accent: '#FFF3EB',
      background: '#FFFBF7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFE9D6',
      borderLight: '#FFF3EB',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFBF7',
      surfaceActive: '#FFF3EB',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'lilac-mist',
    name: 'Lilac Mist',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#E0BBE4',
      primaryLight: '#EDD5F0',
      primaryDark: '#D4A1D9',
      secondary: '#D4A5D8',
      secondaryLight: '#E2C1E5',
      secondaryDark: '#C68FCC',
      accent: '#F7EFF9',
      background: '#FDFAFD',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E2C1E5',
      borderLight: '#F7EFF9',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FDFAFD',
      surfaceActive: '#F7EFF9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'seafoam',
    name: 'Seafoam',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#A8E1D7',
      primaryLight: '#C4EEE5',
      primaryDark: '#8DD3C6',
      secondary: '#9DD9CF',
      secondaryLight: '#BCEAE0',
      secondaryDark: '#82C6BA',
      accent: '#E6F8F4',
      background: '#F7FDFB',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#BCEAE0',
      borderLight: '#E6F8F4',
      success: '#A8E1D7',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E6F8F4',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2C8F7F',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7FDFB',
      surfaceActive: '#E6F8F4',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  // Simple Classic Themes
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#667eea',
      primaryLight: '#a5b4fc',
      primaryDark: '#5568d3',
      secondary: '#48bb78',
      secondaryLight: '#68d391',
      secondaryDark: '#38a169',
      accent: '#ebf4ff',
      background: '#f7fafc',
      surface: '#ffffff',
      text: '#2d3748',
      textSecondary: '#718096',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#a0aec0',
      border: '#cbd5e0',
      borderLight: '#e2e8f0',
      success: '#48bb78',
      warning: '#fbbf24',
      error: '#f56565',
      info: '#4299e1',
      successBg: '#f0fff4',
      warningBg: '#fffbeb',
      errorBg: '#fff5f5',
      infoBg: '#ebf8ff',
      successText: '#2f855a',
      warningText: '#92400e',
      errorText: '#c53030',
      infoText: '#2c5282',
      codeBg: '#2d3748',
      codeText: '#e2e8f0',
      surfaceHover: '#f7fafc',
      surfaceActive: '#edf2f7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#059669',
      primaryLight: '#34d399',
      primaryDark: '#047857',
      secondary: '#0891b2',
      secondaryLight: '#22d3ee',
      secondaryDark: '#0e7490',
      accent: '#d1fae5',
      background: '#f0fdf4',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#a7f3d0',
      borderLight: '#d1fae5',
      success: '#059669',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#0891b2',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#cffafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#0e7490',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#f0fdf4',
      surfaceActive: '#dcfce7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'slate-gray',
    name: 'Slate Gray',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#64748b',
      primaryLight: '#94a3b8',
      primaryDark: '#475569',
      secondary: '#0ea5e9',
      secondaryLight: '#38bdf8',
      secondaryDark: '#0284c7',
      accent: '#f1f5f9',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#1e293b',
      textSecondary: '#64748b',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#94a3b8',
      border: '#cbd5e1',
      borderLight: '#e2e8f0',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#0ea5e9',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#e0f2fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#075985',
      codeBg: '#1e293b',
      codeText: '#f1f5f9',
      surfaceHover: '#f8fafc',
      surfaceActive: '#f1f5f9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#ea580c',
      primaryLight: '#fb923c',
      primaryDark: '#c2410c',
      secondary: '#eab308',
      secondaryLight: '#facc15',
      secondaryDark: '#ca8a04',
      accent: '#ffedd5',
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#1c1917',
      textSecondary: '#57534e',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#1c1917',
      textMuted: '#a8a29e',
      border: '#fed7aa',
      borderLight: '#ffedd5',
      success: '#22c55e',
      warning: '#eab308',
      error: '#dc2626',
      info: '#06b6d4',
      successBg: '#dcfce7',
      warningBg: '#fef9c3',
      errorBg: '#fee2e2',
      infoBg: '#cffafe',
      successText: '#166534',
      warningText: '#854d0e',
      errorText: '#991b1b',
      infoText: '#164e63',
      codeBg: '#1c1917',
      codeText: '#fafaf9',
      surfaceHover: '#fffbeb',
      surfaceActive: '#fef3c7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#7c3aed',
      primaryLight: '#a78bfa',
      primaryDark: '#6d28d9',
      secondary: '#ec4899',
      secondaryLight: '#f472b6',
      secondaryDark: '#db2777',
      accent: '#ede9fe',
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#c4b5fd',
      borderLight: '#ddd6fe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#8b5cf6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#ede9fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#5b21b6',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#faf5ff',
      surfaceActive: '#f3e8ff',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'crimson-red',
    name: 'Crimson Red',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#dc2626',
      primaryLight: '#f87171',
      primaryDark: '#b91c1c',
      secondary: '#f97316',
      secondaryLight: '#fb923c',
      secondaryDark: '#ea580c',
      accent: '#fee2e2',
      background: '#fef2f2',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#fca5a5',
      borderLight: '#fecaca',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#dc2626',
      info: '#3b82f6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#dbeafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#1e40af',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#fef2f2',
      surfaceActive: '#fee2e2',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#1e3a8a',
      primaryLight: '#3b82f6',
      primaryDark: '#1e40af',
      secondary: '#06b6d4',
      secondaryLight: '#22d3ee',
      secondaryDark: '#0891b2',
      accent: '#dbeafe',
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#1e293b',
      textSecondary: '#475569',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#94a3b8',
      border: '#93c5fd',
      borderLight: '#bfdbfe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#dbeafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#1e40af',
      codeBg: '#1e293b',
      codeText: '#f1f5f9',
      surfaceHover: '#eff6ff',
      surfaceActive: '#dbeafe',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#374151',
      primaryLight: '#6b7280',
      primaryDark: '#1f2937',
      secondary: '#9ca3af',
      secondaryLight: '#d1d5db',
      secondaryDark: '#6b7280',
      accent: '#f3f4f6',
      background: '#f9fafb',
      surface: '#ffffff',
      text: '#111827',
      textSecondary: '#4b5563',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#111827',
      textMuted: '#9ca3af',
      border: '#d1d5db',
      borderLight: '#e5e7eb',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      info: '#0284c7',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#e0f2fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#075985',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#f9fafb',
      surfaceActive: '#f3f4f6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
];

export const defaultTheme = themes[0]; // Peach Fuzz 2024

export function getThemeById(id: string): Theme {
  return themes.find((theme) => theme.id === id) || defaultTheme;
}

export function applyTheme(theme: Theme): void {
  const root = document.documentElement;

  // Primary colors
  root.style.setProperty('--color-primary', theme.colors.primary);
  root.style.setProperty('--color-primary-light', theme.colors.primaryLight);
  root.style.setProperty('--color-primary-dark', theme.colors.primaryDark);
  root.style.setProperty('--color-secondary', theme.colors.secondary);
  root.style.setProperty('--color-secondary-light', theme.colors.secondaryLight);
  root.style.setProperty('--color-secondary-dark', theme.colors.secondaryDark);
  root.style.setProperty('--color-accent', theme.colors.accent);

  // Backgrounds and surfaces
  root.style.setProperty('--color-background', theme.colors.background);
  root.style.setProperty('--color-surface', theme.colors.surface);
  root.style.setProperty('--color-surface-hover', theme.colors.surfaceHover);
  root.style.setProperty('--color-surface-active', theme.colors.surfaceActive);
  root.style.setProperty('--color-overlay', theme.colors.overlay);

  // Text colors
  root.style.setProperty('--color-text', theme.colors.text);
  root.style.setProperty('--color-text-secondary', theme.colors.textSecondary);
  root.style.setProperty('--color-text-muted', theme.colors.textMuted);
  root.style.setProperty('--color-text-on-primary', theme.colors.textOnPrimary);
  root.style.setProperty('--color-text-on-secondary', theme.colors.textOnSecondary);

  // Borders
  root.style.setProperty('--color-border', theme.colors.border);
  root.style.setProperty('--color-border-light', theme.colors.borderLight);

  // Status colors (badges/indicators)
  root.style.setProperty('--color-success', theme.colors.success);
  root.style.setProperty('--color-warning', theme.colors.warning);
  root.style.setProperty('--color-error', theme.colors.error);
  root.style.setProperty('--color-info', theme.colors.info);

  // Status backgrounds
  root.style.setProperty('--color-success-bg', theme.colors.successBg);
  root.style.setProperty('--color-warning-bg', theme.colors.warningBg);
  root.style.setProperty('--color-error-bg', theme.colors.errorBg);
  root.style.setProperty('--color-info-bg', theme.colors.infoBg);

  // Status text colors
  root.style.setProperty('--color-success-text', theme.colors.successText);
  root.style.setProperty('--color-warning-text', theme.colors.warningText);
  root.style.setProperty('--color-error-text', theme.colors.errorText);
  root.style.setProperty('--color-info-text', theme.colors.infoText);

  // Code/terminal colors
  root.style.setProperty('--color-code-bg', theme.colors.codeBg);
  root.style.setProperty('--color-code-text', theme.colors.codeText);
}
