// Pantone Color of the Year themes (2015-2024)

export interface Theme {
  id: string;
  name: string;
  year: number;
  pantone: string;
  colors: {
    primary: string;
    primaryLight: string;
    primaryDark: string;
    secondary: string;
    secondaryLight: string;
    secondaryDark: string;
    accent: string;
    background: string;
    surface: string;
    text: string;
    textSecondary: string;
    textOnPrimary: string;
    textOnSecondary: string;
    textMuted: string;
    border: string;
    borderLight: string;
    success: string;
    warning: string;
    error: string;
    info: string;
    successBg: string;
    warningBg: string;
    errorBg: string;
    infoBg: string;
    successText: string;
    warningText: string;
    errorText: string;
    infoText: string;
    codeBg: string;
    codeText: string;
    surfaceHover: string;
    surfaceActive: string;
    overlay: string;
  };
}

export const themes: Theme[] = [
  {
    id: 'peach-fuzz',
    name: 'Peach Fuzz',
    year: 2024,
    pantone: 'PANTONE 13-1023',
    colors: {
      primary: '#FFBE98',
      primaryLight: '#FFD4B8',
      primaryDark: '#E89A72',
      secondary: '#F4A582',
      secondaryLight: '#F8C0A2',
      secondaryDark: '#E08A62',
      accent: '#FFE4D6',
      background: '#FFF8F5',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFD4B8',
      borderLight: '#FFE9DD',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF8F5',
      surfaceActive: '#FFE9DD',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'viva-magenta',
    name: 'Viva Magenta',
    year: 2023,
    pantone: 'PANTONE 18-1750',
    colors: {
      primary: '#BE3455',
      primaryLight: '#D65577',
      primaryDark: '#9B2642',
      secondary: '#E84B6E',
      secondaryLight: '#F06F8C',
      secondaryDark: '#D02750',
      accent: '#FFE4E9',
      background: '#FFF5F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#E2B3BF',
      borderLight: '#F0D9DF',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF5F7',
      surfaceActive: '#FFE4E9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'very-peri',
    name: 'Very Peri',
    year: 2022,
    pantone: 'PANTONE 17-3938',
    colors: {
      primary: '#6667AB',
      primaryLight: '#8889C9',
      primaryDark: '#4F508A',
      secondary: '#9394D1',
      secondaryLight: '#AFAFDF',
      secondaryDark: '#7879B3',
      accent: '#E6E6F5',
      background: '#F7F7FC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#C7C7E2',
      borderLight: '#DCDCEE',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7F7FC',
      surfaceActive: '#E6E6F5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'illuminating-gray',
    name: 'Illuminating + Gray',
    year: 2021,
    pantone: 'PANTONE 17-5104 + 13-0647',
    colors: {
      primary: '#939597',
      primaryLight: '#B8BABC',
      primaryDark: '#6E7072',
      secondary: '#F5DF4D',
      secondaryLight: '#F8E77D',
      secondaryDark: '#E5CF3D',
      accent: '#FFF9D9',
      background: '#F7F7F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E2E8F0',
      borderLight: '#EDF2F7',
      success: '#48BB78',
      warning: '#F5DF4D',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFF9D9',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#975A16',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7F7F7',
      surfaceActive: '#EDF2F7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'classic-blue',
    name: 'Classic Blue',
    year: 2020,
    pantone: 'PANTONE 19-4052',
    colors: {
      primary: '#0F4C81',
      primaryLight: '#4A7BA7',
      primaryDark: '#0A3659',
      secondary: '#5B9BD5',
      secondaryLight: '#8BBAE0',
      secondaryDark: '#4886C5',
      accent: '#D6E8F7',
      background: '#F0F7FF',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#B3D4E8',
      borderLight: '#D6E8F7',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#5B9BD5',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#D6E8F7',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#0F4C81',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F0F7FF',
      surfaceActive: '#D6E8F7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'living-coral',
    name: 'Living Coral',
    year: 2019,
    pantone: 'PANTONE 16-1546',
    colors: {
      primary: '#FF6F61',
      primaryLight: '#FF9287',
      primaryDark: '#E65548',
      secondary: '#FFB5AE',
      secondaryLight: '#FFC8C3',
      secondaryDark: '#FF9C95',
      accent: '#FFE9E6',
      background: '#FFF5F4',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFCCC7',
      borderLight: '#FFE0DD',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFF5F4',
      surfaceActive: '#FFE9E6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'ultra-violet',
    name: 'Ultra Violet',
    year: 2018,
    pantone: 'PANTONE 18-3838',
    colors: {
      primary: '#5F4B8B',
      primaryLight: '#8477AB',
      primaryDark: '#473766',
      secondary: '#9B89BD',
      secondaryLight: '#B5A4CC',
      secondaryDark: '#8774AA',
      accent: '#E8E3F0',
      background: '#F5F3F9',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#D1C4E3',
      borderLight: '#E8E3F0',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#9B89BD',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#E8E3F0',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#473766',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F5F3F9',
      surfaceActive: '#E8E3F0',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'greenery',
    name: 'Greenery',
    year: 2017,
    pantone: 'PANTONE 15-0343',
    colors: {
      primary: '#88B04B',
      primaryLight: '#A8C97B',
      primaryDark: '#6D8C3C',
      secondary: '#B5D47C',
      secondaryLight: '#C8DF9A',
      secondaryDark: '#A0C060',
      accent: '#E8F3D6',
      background: '#F5FAF0',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#D4E5BC',
      borderLight: '#E8F3D6',
      success: '#88B04B',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#E8F3D6',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#6D8C3C',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F5FAF0',
      surfaceActive: '#E8F3D6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'rose-serenity',
    name: 'Rose Quartz + Serenity',
    year: 2016,
    pantone: 'PANTONE 13-1520 + 15-3919',
    colors: {
      primary: '#F7CAC9',
      primaryLight: '#FADED9',
      primaryDark: '#E5B3B2',
      secondary: '#92A8D1',
      secondaryLight: '#AFC0DC',
      secondaryDark: '#7A92C6',
      accent: '#EDF2F9',
      background: '#FBF7F7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E5D4E0',
      borderLight: '#EDF2F9',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#92A8D1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EDF2F9',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FBF7F7',
      surfaceActive: '#EDF2F9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'marsala',
    name: 'Marsala',
    year: 2015,
    pantone: 'PANTONE 18-1438',
    colors: {
      primary: '#955251',
      primaryLight: '#B57876',
      primaryDark: '#764140',
      secondary: '#C9908E',
      secondaryLight: '#D9ADA9',
      secondaryDark: '#B57876',
      accent: '#F0E4E3',
      background: '#FAF5F5',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#FFFFFF',
      textOnSecondary: '#FFFFFF',
      textMuted: '#A0AEC0',
      border: '#DCC9C8',
      borderLight: '#F0E4E3',
      success: '#48BB78',
      warning: '#ED8936',
      error: '#F56565',
      info: '#4299E1',
      successBg: '#F0FFF4',
      warningBg: '#FFFAF0',
      errorBg: '#FFF5F5',
      infoBg: '#EBF8FF',
      successText: '#2F855A',
      warningText: '#C05621',
      errorText: '#C53030',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FAF5F5',
      surfaceActive: '#F0E4E3',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  // Pastel Themes Collection
  {
    id: 'lavender-dream',
    name: 'Lavender Dream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#C7B8EA',
      primaryLight: '#DDD2F4',
      primaryDark: '#B09FDB',
      secondary: '#E0D5F7',
      secondaryLight: '#EDE6FA',
      secondaryDark: '#D3C4F0',
      accent: '#F5F1FF',
      background: '#FDFCFF',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E0D5F7',
      borderLight: '#EDE6FA',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FDFCFF',
      surfaceActive: '#F5F1FF',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#B4E7CE',
      primaryLight: '#CDEFD9',
      primaryDark: '#9BDABF',
      secondary: '#A8E6CF',
      secondaryLight: '#C4F0DD',
      secondaryDark: '#92D9BC',
      accent: '#E8FAF1',
      background: '#F8FFFC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#C4F0DD',
      borderLight: '#E8FAF1',
      success: '#A8E6CF',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8FAF1',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F8555',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F8FFFC',
      surfaceActive: '#E8FAF1',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'powder-blue',
    name: 'Powder Blue',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#B5D8EB',
      primaryLight: '#CEEBF5',
      primaryDark: '#9CC7DD',
      secondary: '#A8D8EA',
      secondaryLight: '#C3E5F0',
      secondaryDark: '#8FC8DC',
      accent: '#E5F4F9',
      background: '#F7FCFE',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#C3E5F0',
      borderLight: '#E5F4F9',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5D8EB',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#E5F4F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7FCFE',
      surfaceActive: '#E5F4F9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'butter-cream',
    name: 'Butter Cream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFF4B8',
      primaryLight: '#FFF9D6',
      primaryDark: '#FFEB9A',
      secondary: '#FFECA8',
      secondaryLight: '#FFF3C8',
      secondaryDark: '#FFE590',
      accent: '#FFFBED',
      background: '#FFFEF8',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFF3C8',
      borderLight: '#FFFBED',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFEF8',
      surfaceActive: '#FFFBED',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFD1DC',
      primaryLight: '#FFE4EC',
      primaryDark: '#FFBDCC',
      secondary: '#FFC9DD',
      secondaryLight: '#FFDEE8',
      secondaryDark: '#FFB4D0',
      accent: '#FFF0F5',
      background: '#FFFAFC',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFDEE8',
      borderLight: '#FFF0F5',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFAFC',
      surfaceActive: '#FFF0F5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'peach-cream',
    name: 'Peach Cream',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#FFD7BA',
      primaryLight: '#FFE6D5',
      primaryDark: '#FFC7A0',
      secondary: '#FFDAB9',
      secondaryLight: '#FFE9D6',
      secondaryDark: '#FFC89E',
      accent: '#FFF3EB',
      background: '#FFFBF7',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#FFE9D6',
      borderLight: '#FFF3EB',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FFFBF7',
      surfaceActive: '#FFF3EB',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'lilac-mist',
    name: 'Lilac Mist',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#E0BBE4',
      primaryLight: '#EDD5F0',
      primaryDark: '#D4A1D9',
      secondary: '#D4A5D8',
      secondaryLight: '#E2C1E5',
      secondaryDark: '#C68FCC',
      accent: '#F7EFF9',
      background: '#FDFAFD',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#4A5568',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#E2C1E5',
      borderLight: '#F7EFF9',
      success: '#A8D5BA',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E8F5ED',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2F7D4A',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#FDFAFD',
      surfaceActive: '#F7EFF9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'seafoam',
    name: 'Seafoam',
    year: 2025,
    pantone: 'Pastel Collection',
    colors: {
      primary: '#A8E1D7',
      primaryLight: '#C4EEE5',
      primaryDark: '#8DD3C6',
      secondary: '#9DD9CF',
      secondaryLight: '#BCEAE0',
      secondaryDark: '#82C6BA',
      accent: '#E6F8F4',
      background: '#F7FDFB',
      surface: '#FFFFFF',
      text: '#1A202C',
      textSecondary: '#2D3748',
      textOnPrimary: '#1A202C',
      textOnSecondary: '#1A202C',
      textMuted: '#A0AEC0',
      border: '#BCEAE0',
      borderLight: '#E6F8F4',
      success: '#A8E1D7',
      warning: '#FFD3A5',
      error: '#FFB3BA',
      info: '#B5C9E8',
      successBg: '#E6F8F4',
      warningBg: '#FFF5EB',
      errorBg: '#FFE8EA',
      infoBg: '#EAF1F9',
      successText: '#2C8F7F',
      warningText: '#B8651B',
      errorText: '#B33A3F',
      infoText: '#2C5282',
      codeBg: '#1A202C',
      codeText: '#E2E8F0',
      surfaceHover: '#F7FDFB',
      surfaceActive: '#E6F8F4',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  // Simple Classic Themes
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#667eea',
      primaryLight: '#a5b4fc',
      primaryDark: '#5568d3',
      secondary: '#48bb78',
      secondaryLight: '#68d391',
      secondaryDark: '#38a169',
      accent: '#ebf4ff',
      background: '#f7fafc',
      surface: '#ffffff',
      text: '#2d3748',
      textSecondary: '#718096',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#a0aec0',
      border: '#cbd5e0',
      borderLight: '#e2e8f0',
      success: '#48bb78',
      warning: '#fbbf24',
      error: '#f56565',
      info: '#4299e1',
      successBg: '#f0fff4',
      warningBg: '#fffbeb',
      errorBg: '#fff5f5',
      infoBg: '#ebf8ff',
      successText: '#2f855a',
      warningText: '#92400e',
      errorText: '#c53030',
      infoText: '#2c5282',
      codeBg: '#2d3748',
      codeText: '#e2e8f0',
      surfaceHover: '#f7fafc',
      surfaceActive: '#edf2f7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#059669',
      primaryLight: '#34d399',
      primaryDark: '#047857',
      secondary: '#0891b2',
      secondaryLight: '#22d3ee',
      secondaryDark: '#0e7490',
      accent: '#d1fae5',
      background: '#f0fdf4',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#a7f3d0',
      borderLight: '#d1fae5',
      success: '#059669',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#0891b2',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#cffafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#0e7490',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#f0fdf4',
      surfaceActive: '#dcfce7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'slate-gray',
    name: 'Slate Gray',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#64748b',
      primaryLight: '#94a3b8',
      primaryDark: '#475569',
      secondary: '#0ea5e9',
      secondaryLight: '#38bdf8',
      secondaryDark: '#0284c7',
      accent: '#f1f5f9',
      background: '#f8fafc',
      surface: '#ffffff',
      text: '#1e293b',
      textSecondary: '#64748b',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#94a3b8',
      border: '#cbd5e1',
      borderLight: '#e2e8f0',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#0ea5e9',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#e0f2fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#075985',
      codeBg: '#1e293b',
      codeText: '#f1f5f9',
      surfaceHover: '#f8fafc',
      surfaceActive: '#f1f5f9',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'sunset-orange',
    name: 'Sunset Orange',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#ea580c',
      primaryLight: '#fb923c',
      primaryDark: '#c2410c',
      secondary: '#eab308',
      secondaryLight: '#facc15',
      secondaryDark: '#ca8a04',
      accent: '#ffedd5',
      background: '#fffbeb',
      surface: '#ffffff',
      text: '#1c1917',
      textSecondary: '#57534e',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#1c1917',
      textMuted: '#a8a29e',
      border: '#fed7aa',
      borderLight: '#ffedd5',
      success: '#22c55e',
      warning: '#eab308',
      error: '#dc2626',
      info: '#06b6d4',
      successBg: '#dcfce7',
      warningBg: '#fef9c3',
      errorBg: '#fee2e2',
      infoBg: '#cffafe',
      successText: '#166534',
      warningText: '#854d0e',
      errorText: '#991b1b',
      infoText: '#164e63',
      codeBg: '#1c1917',
      codeText: '#fafaf9',
      surfaceHover: '#fffbeb',
      surfaceActive: '#fef3c7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#7c3aed',
      primaryLight: '#a78bfa',
      primaryDark: '#6d28d9',
      secondary: '#ec4899',
      secondaryLight: '#f472b6',
      secondaryDark: '#db2777',
      accent: '#ede9fe',
      background: '#faf5ff',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#c4b5fd',
      borderLight: '#ddd6fe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#8b5cf6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#ede9fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#5b21b6',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#faf5ff',
      surfaceActive: '#f3e8ff',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'crimson-red',
    name: 'Crimson Red',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#dc2626',
      primaryLight: '#f87171',
      primaryDark: '#b91c1c',
      secondary: '#f97316',
      secondaryLight: '#fb923c',
      secondaryDark: '#ea580c',
      accent: '#fee2e2',
      background: '#fef2f2',
      surface: '#ffffff',
      text: '#1f2937',
      textSecondary: '#6b7280',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9ca3af',
      border: '#fca5a5',
      borderLight: '#fecaca',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#dc2626',
      info: '#3b82f6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#dbeafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#1e40af',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#fef2f2',
      surfaceActive: '#fee2e2',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#1e3a8a',
      primaryLight: '#3b82f6',
      primaryDark: '#1e40af',
      secondary: '#06b6d4',
      secondaryLight: '#22d3ee',
      secondaryDark: '#0891b2',
      accent: '#dbeafe',
      background: '#eff6ff',
      surface: '#ffffff',
      text: '#1e293b',
      textSecondary: '#475569',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#94a3b8',
      border: '#93c5fd',
      borderLight: '#bfdbfe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#dbeafe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#1e40af',
      codeBg: '#1e293b',
      codeText: '#f1f5f9',
      surfaceHover: '#eff6ff',
      surfaceActive: '#dbeafe',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    year: 2025,
    pantone: 'Classic Collection',
    colors: {
      primary: '#374151',
      primaryLight: '#6b7280',
      primaryDark: '#1f2937',
      secondary: '#9ca3af',
      secondaryLight: '#d1d5db',
      secondaryDark: '#6b7280',
      accent: '#f3f4f6',
      background: '#f9fafb',
      surface: '#ffffff',
      text: '#111827',
      textSecondary: '#4b5563',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#111827',
      textMuted: '#9ca3af',
      border: '#d1d5db',
      borderLight: '#e5e7eb',
      success: '#059669',
      warning: '#d97706',
      error: '#dc2626',
      info: '#0284c7',
      successBg: '#d1fae5',
      warningBg: '#fef3c7',
      errorBg: '#fee2e2',
      infoBg: '#e0f2fe',
      successText: '#065f46',
      warningText: '#92400e',
      errorText: '#991b1b',
      infoText: '#075985',
      codeBg: '#1f2937',
      codeText: '#f3f4f6',
      surfaceHover: '#f9fafb',
      surfaceActive: '#f3f4f6',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  // Professional & Elegant Themes
  {
    id: 'nord',
    name: 'Nord',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#5e81ac',
      primaryLight: '#81a1c1',
      primaryDark: '#4c566a',
      secondary: '#88c0d0',
      secondaryLight: '#8fbcbb',
      secondaryDark: '#5e81ac',
      accent: '#eceff4',
      background: '#f8f9fa',
      surface: '#ffffff',
      text: '#2e3440',
      textSecondary: '#4c566a',
      textOnPrimary: '#eceff4',
      textOnSecondary: '#2e3440',
      textMuted: '#7c8694',
      border: '#d8dee9',
      borderLight: '#e5e9f0',
      success: '#a3be8c',
      warning: '#ebcb8b',
      error: '#bf616a',
      info: '#5e81ac',
      successBg: '#f0f4ec',
      warningBg: '#fdf8ec',
      errorBg: '#f9ecec',
      infoBg: '#ebf0f5',
      successText: '#5f7c52',
      warningText: '#8a6d3b',
      errorText: '#8b3a3f',
      infoText: '#3d5671',
      codeBg: '#2e3440',
      codeText: '#eceff4',
      surfaceHover: '#f8f9fa',
      surfaceActive: '#eceff4',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#7aa2f7',
      primaryLight: '#9ece6a',
      primaryDark: '#3d59a1',
      secondary: '#bb9af7',
      secondaryLight: '#c0a7e7',
      secondaryDark: '#9d7cd8',
      accent: '#e0e8f7',
      background: '#f5f7fa',
      surface: '#ffffff',
      text: '#1a1b26',
      textSecondary: '#3d4964',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#1a1b26',
      textMuted: '#8994b0',
      border: '#d0d7e6',
      borderLight: '#e0e8f7',
      success: '#9ece6a',
      warning: '#e0af68',
      error: '#f7768e',
      info: '#7aa2f7',
      successBg: '#f0f7ec',
      warningBg: '#fdf5e6',
      errorBg: '#fef0f3',
      infoBg: '#eff4fb',
      successText: '#5a8040',
      warningText: '#9a7a3f',
      errorText: '#b4505f',
      infoText: '#4d68a0',
      codeBg: '#1a1b26',
      codeText: '#c0caf5',
      surfaceHover: '#f5f7fa',
      surfaceActive: '#e0e8f7',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#bd93f9',
      primaryLight: '#cdb4f9',
      primaryDark: '#9d73d9',
      secondary: '#ff79c6',
      secondaryLight: '#ff92d0',
      secondaryDark: '#e65fb3',
      accent: '#f8f8f2',
      background: '#fafafa',
      surface: '#ffffff',
      text: '#282a36',
      textSecondary: '#44475a',
      textOnPrimary: '#f8f8f2',
      textOnSecondary: '#282a36',
      textMuted: '#6272a4',
      border: '#d0d5e3',
      borderLight: '#e8eaf0',
      success: '#50fa7b',
      warning: '#f1fa8c',
      error: '#ff5555',
      info: '#8be9fd',
      successBg: '#edfcf2',
      warningBg: '#fefce8',
      errorBg: '#ffeded',
      infoBg: '#e8fcfe',
      successText: '#2d9350',
      warningText: '#8a8c2f',
      errorText: '#cc3333',
      infoText: '#4ba9b5',
      codeBg: '#282a36',
      codeText: '#f8f8f2',
      surfaceHover: '#fafafa',
      surfaceActive: '#f0f1f5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#61afef',
      primaryLight: '#7ec4f5',
      primaryDark: '#4a9ad9',
      secondary: '#c678dd',
      secondaryLight: '#d19ae6',
      secondaryDark: '#b061c8',
      accent: '#e6eef5',
      background: '#f6f7f9',
      surface: '#ffffff',
      text: '#282c34',
      textSecondary: '#5c6370',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#282c34',
      textMuted: '#848b98',
      border: '#d0d4db',
      borderLight: '#e6e9ef',
      success: '#98c379',
      warning: '#e5c07b',
      error: '#e06c75',
      info: '#61afef',
      successBg: '#f0f7ec',
      warningBg: '#fdf6e8',
      errorBg: '#fceeed',
      infoBg: '#edf5fb',
      successText: '#5f8149',
      warningText: '#9a824f',
      errorText: '#a84a52',
      infoText: '#3d7cb8',
      codeBg: '#282c34',
      codeText: '#abb2bf',
      surfaceHover: '#f6f7f9',
      surfaceActive: '#e6e9ef',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#0969da',
      primaryLight: '#3184e4',
      primaryDark: '#0550ae',
      secondary: '#6e7781',
      secondaryLight: '#8c959f',
      secondaryDark: '#57606a',
      accent: '#f6f8fa',
      background: '#ffffff',
      surface: '#ffffff',
      text: '#24292f',
      textSecondary: '#57606a',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#24292f',
      textMuted: '#8c959f',
      border: '#d0d7de',
      borderLight: '#e5e9ee',
      success: '#1a7f37',
      warning: '#9a6700',
      error: '#cf222e',
      info: '#0969da',
      successBg: '#dafbe1',
      warningBg: '#fff8c5',
      errorBg: '#ffebe9',
      infoBg: '#ddf4ff',
      successText: '#0f5323',
      warningText: '#7d4e00',
      errorText: '#a40e26',
      infoText: '#0550ae',
      codeBg: '#f6f8fa',
      codeText: '#24292f',
      surfaceHover: '#f6f8fa',
      surfaceActive: '#e5e9ee',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#268bd2',
      primaryLight: '#4ea3dc',
      primaryDark: '#1f73b8',
      secondary: '#2aa198',
      secondaryLight: '#52b9b0',
      secondaryDark: '#21897f',
      accent: '#eee8d5',
      background: '#fdf6e3',
      surface: '#ffffff',
      text: '#002b36',
      textSecondary: '#586e75',
      textOnPrimary: '#fdf6e3',
      textOnSecondary: '#002b36',
      textMuted: '#93a1a1',
      border: '#d9cdb3',
      borderLight: '#e9dfc5',
      success: '#859900',
      warning: '#b58900',
      error: '#dc322f',
      info: '#268bd2',
      successBg: '#f0f3e8',
      warningBg: '#f9f3e0',
      errorBg: '#fbeae9',
      infoBg: '#e8f2f7',
      successText: '#5a6600',
      warningText: '#7d5d00',
      errorText: '#a1211f',
      infoText: '#1b5f91',
      codeBg: '#002b36',
      codeText: '#839496',
      surfaceHover: '#fdf6e3',
      surfaceActive: '#eee8d5',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'material',
    name: 'Material',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#1976d2',
      primaryLight: '#42a5f5',
      primaryDark: '#1565c0',
      secondary: '#424242',
      secondaryLight: '#616161',
      secondaryDark: '#212121',
      accent: '#e3f2fd',
      background: '#fafafa',
      surface: '#ffffff',
      text: '#212121',
      textSecondary: '#757575',
      textOnPrimary: '#ffffff',
      textOnSecondary: '#ffffff',
      textMuted: '#9e9e9e',
      border: '#e0e0e0',
      borderLight: '#eeeeee',
      success: '#4caf50',
      warning: '#ff9800',
      error: '#f44336',
      info: '#2196f3',
      successBg: '#e8f5e9',
      warningBg: '#fff3e0',
      errorBg: '#ffebee',
      infoBg: '#e3f2fd',
      successText: '#2e7d32',
      warningText: '#e65100',
      errorText: '#c62828',
      infoText: '#1565c0',
      codeBg: '#263238',
      codeText: '#eeffff',
      surfaceHover: '#fafafa',
      surfaceActive: '#eeeeee',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#458588',
      primaryLight: '#83a598',
      primaryDark: '#076678',
      secondary: '#b16286',
      secondaryLight: '#d3869b',
      secondaryDark: '#8f3f71',
      accent: '#f2e5bc',
      background: '#fbf1c7',
      surface: '#ffffff',
      text: '#3c3836',
      textSecondary: '#504945',
      textOnPrimary: '#fbf1c7',
      textOnSecondary: '#fbf1c7',
      textMuted: '#928374',
      border: '#d5c4a1',
      borderLight: '#ebdbb2',
      success: '#98971a',
      warning: '#d79921',
      error: '#cc241d',
      info: '#458588',
      successBg: '#f0f2e5',
      warningBg: '#fdf5e0',
      errorBg: '#fbeae9',
      infoBg: '#e9f0f3',
      successText: '#79740e',
      warningText: '#b57614',
      errorText: '#9d0006',
      infoText: '#076678',
      codeBg: '#3c3836',
      codeText: '#ebdbb2',
      surfaceHover: '#fbf1c7',
      surfaceActive: '#f2e5bc',
      overlay: 'rgba(0, 0, 0, 0.5)',
    },
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    year: 2025,
    pantone: 'Professional Collection',
    colors: {
      primary: '#1e66f5',
      primaryLight: '#7287fd',
      primaryDark: '#04a5e5',
      secondary: '#8839ef',
      secondaryLight: '#ea76cb',
      secondaryDark: '#7c3aed',
      accent: '#dce0e8',
      background: '#eff1f5',
      surface: '#ffffff',
      text: '#4c4f69',
      textSecondary: '#5c5f77',
      textOnPrimary: '#eff1f5',
      textOnSecondary: '#eff1f5',
      textMuted: '#9ca0b0',
      border: '#ccd0da',
      borderLight: '#dce0e8',
      success: '#40a02b',
      warning: '#df8e1d',
      error: '#d20f39',
      info: '#1e66f5',
      successBg: '#e8f5e9',
      warningBg: '#fff3e0',
      errorBg: '#ffebee',
      infoBg: '#e3f2fd',
      successText: '#2d6a22',
      warningText: '#a66815',
      errorText: '#9c0c2c',
      infoText: '#1751c4',
      codeBg: '#4c4f69',
      codeText: '#eff1f5',
      surfaceHover: '#eff1f5',
      surfaceActive: '#dce0e8',
      overlay: 'rgba(76, 79, 105, 0.5)',
    },
  },
];

export const defaultTheme = themes.find((theme) => theme.id === 'nord') || themes[0]; // Nord

export function getThemeById(id: string): Theme {
  return themes.find((theme) => theme.id === id) || defaultTheme;
}

export function applyTheme(theme: Theme): void {
  const root = document.documentElement;

  // Primary colors
  root.style.setProperty('--color-primary', theme.colors.primary);
  root.style.setProperty('--color-primary-light', theme.colors.primaryLight);
  root.style.setProperty('--color-primary-dark', theme.colors.primaryDark);
  root.style.setProperty('--color-secondary', theme.colors.secondary);
  root.style.setProperty('--color-secondary-light', theme.colors.secondaryLight);
  root.style.setProperty('--color-secondary-dark', theme.colors.secondaryDark);
  root.style.setProperty('--color-accent', theme.colors.accent);

  // Backgrounds and surfaces
  root.style.setProperty('--color-background', theme.colors.background);
  root.style.setProperty('--color-surface', theme.colors.surface);
  root.style.setProperty('--color-surface-hover', theme.colors.surfaceHover);
  root.style.setProperty('--color-surface-active', theme.colors.surfaceActive);
  root.style.setProperty('--color-overlay', theme.colors.overlay);

  // Text colors
  root.style.setProperty('--color-text', theme.colors.text);
  root.style.setProperty('--color-text-secondary', theme.colors.textSecondary);
  root.style.setProperty('--color-text-muted', theme.colors.textMuted);
  root.style.setProperty('--color-text-on-primary', theme.colors.textOnPrimary);
  root.style.setProperty('--color-text-on-secondary', theme.colors.textOnSecondary);

  // Borders
  root.style.setProperty('--color-border', theme.colors.border);
  root.style.setProperty('--color-border-light', theme.colors.borderLight);

  // Status colors (badges/indicators)
  root.style.setProperty('--color-success', theme.colors.success);
  root.style.setProperty('--color-warning', theme.colors.warning);
  root.style.setProperty('--color-error', theme.colors.error);
  root.style.setProperty('--color-info', theme.colors.info);

  // Status backgrounds
  root.style.setProperty('--color-success-bg', theme.colors.successBg);
  root.style.setProperty('--color-warning-bg', theme.colors.warningBg);
  root.style.setProperty('--color-error-bg', theme.colors.errorBg);
  root.style.setProperty('--color-info-bg', theme.colors.infoBg);

  // Status text colors
  root.style.setProperty('--color-success-text', theme.colors.successText);
  root.style.setProperty('--color-warning-text', theme.colors.warningText);
  root.style.setProperty('--color-error-text', theme.colors.errorText);
  root.style.setProperty('--color-info-text', theme.colors.infoText);

  // Code/terminal colors
  root.style.setProperty('--color-code-bg', theme.colors.codeBg);
  root.style.setProperty('--color-code-text', theme.colors.codeText);
}
